### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/python-flask-setup#3]
The default styling that is being used isn't quite up to par. 

Navbar, colors, and the top border all seem off.

**Comment by c-schwarze** [comment]
@josiahtillman This is a low priority, but if you want to clean this up at some point, that would be great.

We can talk more about what this should look like when you get to this.

**Comment by c-schwarze** [comment]
#2 is certainly related.

**Comment by josiahtillman** [comment]
This is done
